### ISSUE TITLE
Feature of `Hubungi admin`

### ISSUE THREAD

**Issue by faridfirdautama** [AgungTriatna/final-project#7]
What kind of `view` did you want to render if a brand new user access your homepage for the first time ?
`New Register` or just call the admin by phone and let admin login then register new user admin by exist admin.

**Comment by DandiLesmana25** [comment]
kalo intruksi dosennya  yang nginput peminjaman sebaiknya dari user bang

**Comment by faridfirdautama** [comment]
Pull request terakhir saya, user baru sudah bisa otomatis input peminjaman karena role-nya sudah jadi admin. Sebelumnya hanya admin yang bisa input peminjaman.

Kalo mau tes, coba : 
- Daftarkan user baru
- logout
- login dengan user yang baru didaftarkan
- input peminjaman untuk si user sendiri
